<a href="https://colab.research.google.com/github/Mahiman001/Data-Science-learning-practice/blob/main/SQL_ALONG_WITH_PYTHON1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
conn = sqlite3.connect(":memory:")

In [ ]:
df = pd.read_csv("messy_customer_sales_data.csv")
df.head()

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India

In [ ]:
df.to_sql( "customer_sales",conn,if_exists= "replace",index =False)

10200

In [ ]:
query = """
SELECT * FROM customer_sales
LIMIT 300
"""
pd.read_sql(query,conn)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,None,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
295,CUST2277,Jose Griffin,F,59.0,Delhi,2025-01-09,2025-01-26,23674.0,NaN,robert16@example.com,3689222898,India
296,CUST7503,Pamela Arnold,f,41.0,bangalore,2022-11-24,2024-12-08,6418.0,2.0,alexandra58@example.org,8630370964,India
297,CUST5403,Nicole Moore,MALE,25.0,Hyderabad,2024-06-21,2024-10-27,24003.0,6.0,cartertonya@example.com,5786494501,India
298,None,Jeffery Long,MALE,54.0,chennai,2022-12-10,2025-05-27,41085.0,7.0,vincent12@example.org,2808140334,India
299,CUST8461,David Mora,F,51.0,kolkata,2022-11-25,2025-05-08,NaN,2.0,ydodson@example.org,7476405134,India

In [ ]:
query = """
SELECT * FROM customer_sales
WHERE Age > 48
LIMIT 10
"""
pd.read_sql(query,conn)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,None,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST1303,Sara Fuller,FEMALE,52.0,HYDERABAD,2025-04-11,2025-06-29,15663.0,4.0,alexandernicholas@example.org,1168031413,India
4,CUST8398,James Ruiz,male,59.0,chennai,2024-08-07,2025-09-03,39876.0,4.0,benjamin18@example.org,5825026489,India
5,CUST4080,Jacqueline Chen,MALE,65.0,hyderabad,2023-09-21,2025-03-11,18020.0,7.0,nicholas29@example.com,4062112650,InDia
6,CUST9469,Randall Johnson,F,61.0,Delhi,2024-05-25,2025-02-24,40633.0,3.0,kylecurry@example.net,321626348,India
7,CUST3268,Adam Drake,MALE,54.0 years,bangalore,2024-07-21,2024-12-24,3371.0,NaN,simmonsmorgan@example.com,3458126917,India
8,CUST7752,Joshua Hayes,F,55.0,Bangalore,2022-07-07,2025-03-03,45923.0,NaN,leejoseph@example.net,8041674560,India
9,CUST2922,Brittany Young,male,69.0,Hyderabad,2022-01-23,2025-03-26,9280.0,NaN,dchavez@example.net,7345041032,IND

In [ ]:
query = """
SELECT * FROM customer_sales
WHERE Age !=48
LIMIT 10
"""
pd.read_sql(query,conn)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,None,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
5,CUST3651,Laura Vincent,male,18.0,BANGALORE,2024-06-16,2025-04-25,NaN,3.0,ymiranda@example.net,6917110630,India
6,CUST10438,Timothy Dunlap,F,43.0 years,Hyderabad,2025-03-16,2025-04-25,18355.0,9.0,christopheranderson@example.net,9981404428,india
7,CUST5189,Sabrina Miller,F,40.0 years,CHENNAI,2025-07-07,2024-10-30,NaN,10.0,shepardcolton@example.net,6233441825,India
8,CUST8237,Mr. Thomas Garcia,F,26.0,None,2025-05-24,2024-10-15,28206.0,NaN,heidimartinez@example.org,1225343854,InDia
9,CUST3260,Jason Mack,MALE,32.0,HYDERABAD,2024-08-14,2025-01-20,48115.0,8.0,campbellrobert@example.com,8366856220,India

In [ ]:
query = """
select * from customer_sales
WHERE  City LIKE  '%KOLKATA%'
LIMIT 10
"""
# HERE MY = THING DID NOT WORK AS THERE WERE  SPACES  IN THE COLUMN NAME AND MANY OTHER VARIABLES AND
# I COULDNT SEE IT SO I USED LIKE FUNCTION TO GET THE NAMES
pd.read_sql(query,conn)

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST1516,William Day,F,None,kolkata,2021-05-02,2025-06-09,27663.0,10.0,richard34@example.net,9463089646,None
2,CUST5950,Brad Lee,FEMALE,61.0 years,Kolkata,2024-12-01,2025-01-26,38155.0,4.0,mossbrent@example.org,6011409712,India
3,CUST2485,Timothy Clark,f,56.0,Kolkata,2022-01-13,2024-11-01,44088.0,5.0,collinsamy@example.net,8156439211,India
4,CUST4289,Anthony Ayala,MALE,68.0,Kolkata,2021-02-17,None,21309.0,5.0,rebekahjennings@example.org,4556467749,India
5,CUST1773,Samuel Wong,m,43.0,KOLKATA,2023-07-04,2025-07-28,23058.0,6.0,michaelchang@example.org,3516454653,India
6,CUST3144,Nancy Scott,None,27.0,Kolkata,2021-06-23,2025-06-05,NaN,6.0,smithcharles@example.org,34292861,IND
7,CUST4352,Cynthia Nguyen,m,32.0,Kolkata,2023-02-10,2025-01-25,2050.0,3.0,tonyabriggs@example.net,7490979405,India
8,CUST2280,Daniel Freeman,male,48.0,kolkata,2025-02-26,2025-09-18,NaN,2.0,georgemaynard@example.net,3984970470,India
9,CUST2968,Christopher Nelson,male,37.0,kolkata,2025-06-12,None,34314.0,3.0,gina98@example.net,163159910,India

In [ ]:
query = """ select count(*) from  customer_sales
"""
pd.read_sql(query,conn)

   count(*)
0     10200

In [ ]:
query = """ select count(Age)from customer_sales
"""
pd.read_sql(query,conn)

   count(Age)
0        9249

In [ ]:
query =""" select AVG(Age) from customer_sales
"""
pd.read_sql(query,conn)

    AVG(Age)
0  43.393772

In [ ]:
query =""" select Min(Age) from customer_sales
"""
pd.read_sql(query,conn)

  Min(Age)
0      -10

In [ ]:
query =""" select Max(Age) from customer_sales
"""
pd.read_sql(query,conn)

    Max(Age)
0  nan years

In [ ]:
query = """ select City,avg(Purchase_Amount) as avg_purchase_amount from customer_sales
where Age > 45
and Feedback_Score > 5.0
group by city
order by avg_purchase_amount
"""
pd.read_sql(query,conn)

           City  avg_purchase_amount
0      CHENNAI          20583.327869
1      KOLKATA          21218.015873
2    hyderabad          22520.037975
3       mumbai          23323.534483
4      Kolkata          23506.695364
5      kolkata          23903.456522
6    HYDERABAD          24160.689189
7       Mumbai          24166.493333
8    Hyderabad          24298.519084
9        Delhi          24322.944056
10         None         24609.670103
11     Chennai          24809.781022
12   BANGALORE          25065.814286
13   Bangalore          25168.938776
14     chennai          25788.754098
15       delhi          26348.102041
16       DELHI          27213.452830
17      MUMBAI          28758.945205
18   bangalore         171173.900000

In [ ]:
query =""" select trim(upper(City)),avg(Purchase_Amount) as avg_purchase_amount,
case when Feedback_Score >5.0  then 'Positive'
     when Feedback_Score = 5.0 then 'Mixed'
ELSE 'Negative'
end as Feedback_Type,
count(*)as total_customers
from customer_sales
where City is not null
group by trim(upper(City)),Feedback_Type
order by avg_purchase_amount
"""
pd.read_sql(query,conn)

   trim(upper(City))  avg_purchase_amount Feedback_Type  total_customers
0            CHENNAI         23453.820122      Negative              725
1          BANGALORE         23815.945736         Mixed              140
2            KOLKATA         23980.026891      Positive              662
3          HYDERABAD         24071.494845         Mixed              105
4            CHENNAI         24155.962901      Positive              677
5            KOLKATA         24604.916667      Negative              736
6             MUMBAI         24615.383459         Mixed              140
7             MUMBAI         24713.741732      Positive              697
8              DELHI         24840.837971      Positive              683
9          HYDERABAD         24939.417840      Positive              704
10             DELHI         25273.904321      Negative              705
11         BANGALORE         25403.520593      Negative              683
12         HYDERABAD         25521.733547      Negative              705
13           CHENNAI         25697.452174         Mixed              129
14             DELHI         26023.785714         Mixed              122
15         BANGALORE         41231.654687      Positive              696
16            MUMBAI         56128.150470      Negative              720
17           KOLKATA         96274.867647         Mixed              155